### ISSUE TITLE
Plugin not working with FC v2.5.10

### ISSUE THREAD

**Issue by 1CM69** [Rolf-Hempel/MoonPanoramaMaker#1]
Hi,
I am trying to use the plugin with FireCapture v2.5.10 x64, the latest version as there is no longer a v2.5 beta version of FC.
Although I have downloaded v0.9.3 of MPM and can 'Dry Run' using Stellarium & Stellarium Scope, FireCapture does not recognise the MPM plugin.

MPM is not showing in the PreProcessing list of FireCapture.

I realise that the latest version of MPM is for v2.5BETA9 of FC.

Are you updating the plugin for use with v2.5.10 release of FC?

**Comment by Rolf-Hempel** [comment]
Hi,
As I wrote on Cloudy Nights, I will look into this issue. MPM uses the FireCapture plugin interface version 1.1. So far I didn't hear that there is a new interface version, so I would assume that MPM should work with FireCapture 2.5.10 x64. I must admit, however, that I don't understand FireCapture's versioning scheme, so I just don't know what to do. I dropped Torsten Edelmann a note to find out. I will do my best to re-establish compatibility.

**Comment by Rolf-Hempel** [comment]
Hi,

After Torsten had confirmed that there is no change in the plugin interface, and that MPM is still working on his computer, today I downloaded the new FC v2.5 64-bit as well. I copied the MoonPanoramaMaker folder into the 64-bit plugin directory (as Torsten described above).

When I started FC, in the preprocessing section there was an empty list. I suspect that this is what you got as well. If you click on the empty list entry, a window opens which tells you that the MoonPanormaMaker plubin is available. If you click on the MoonPanoramaMaker entry, the window closes. Now you see the MoonPanoramaMaker entry in the preprocessing list, and everything works as before. I tested the whole setup (PC, MPM plugin, MPM, Simulator), and it worked just fine.

I suspect that you were misled by the empty preprocessing list. Does the solution I described work for you?

**Comment by 1CM69** [comment]
Hi Rolf,
I have it working now but only because of one sentence that you wrote above "I copied MoonPanoramamaker folder....."
You see, I was under the impression that I only needed to copy the MPM jar file to the plugin folder of FC and not the parent folder that contains the jar file.
I have now copied the parent folder that contains the MPM jar to the FC plugins folder & all is woring perfectly, thank you.
