### ISSUE TITLE
pmatic - colaboration

### ISSUE THREAD

**Issue by poggenpower** [Rolf-Hempel/MoonPanoramaMaker#10]
Hi Rolf, 
Sorry for hijacking the issue tracker from another project, to get in contact.
I saw you did a lot of changes to the LarsMichelsen/pmatic project, but kept it in your repo. As Lars has sadly given up this project, I have some questions about this project. 
Are your changes to the project general bugfixes and features or is it more a tracking of your own customizations. 
I am also interested in this project and want to start with the most latest version/feature set. 
I am also interested in bringing all changes from the other contributors back into one upstream repository to make I easier for others to use this project. 

May be you want to leave a short message here if you are interested in some exchange about the project, than we can switch over to an communication channel that is more appropriate.

Thanks 
  Thomas

**Comment by Rolf-Hempel** [comment]
Hi Thomas,

No problem with the hijacking. I suggest you send me an e-mail to rolf6419@gmx.de to start a private conversation on pmatic.

Your name sounds like you are German / Austrian / Swiss. If that's true, we can switch to German.

All the best
 Rolf
