### ISSUE TITLE
ImportError: No module named Image

### ISSUE THREAD

**Issue by kaythriemer** [Rolf-Hempel/MoonPanoramaMaker#2]
Hi Rolf,
I want to try MoonPanoramaMaker and I downloaded the "MoonPanoramaMaker-master" from git.
As described in users guide I installed Python(x,y)-2.7.10  and activated all Python features/libraries during installation. (I am not so familiar with Python and I dont know, if feature is the correct description.)

After that I installed pyephem using "pip install pyephem".

Now I want to start MPM with "python moon_panorama_maker.py" and I am getting following output:
C:\Users\lux\MoonPanoramaMaker-master\Source>python moon_panorama_maker.py
Traceback (most recent call last):
  File "moon_panorama_maker.py", line 38, in <module>
    from workflow import Workflow
  File "C:\Users\lux\MoonPanoramaMaker-master\Source\workflow.py", line 30, in <
module>
    from alignment import Alignment
  File "C:\Users\lux\MoonPanoramaMaker-master\Source\alignment.py", line 34, in
<module>
    from image_shift import ImageShift
  File "C:\Users\lux\MoonPanoramaMaker-master\Source\image_shift.py", line 30, in <module>
    from Image import fromarray
ImportError: No module named Image

I have "googled" to find the reason for this issue, but "pillow" is already installed.
C:\Users\lux\MoonPanoramaMaker-master\Source>pip install pyephem
Requirement already satisfied: pyephem in c:\python27\lib\site-packages

C:\Users\lux\MoonPanoramaMaker-master\Source>pip install pillow
Requirement already satisfied: pillow in c:\python27\lib\site-packages

Do you have an idea, what library could be missing ? 
Or any other suggestion how to get it running.

Thank you.

Regards,
Kay.

**Comment by Rolf-Hempel** [comment]
Hi Kay,

If you are not familiar with Python, it is not a good idea to work at the source code level. Why don't you just install the complete software using the Windows installer which you can download from the release page (I recommend using the newest release 0.9.3).

To get familiar with using the software, please read the user guide (it comes with the installation) and have a look at the discussions on "Cloudy Nights". You will find a link to the thread on the MPM home page.

Have fun with the MoonPanoramaMaker!

Best wishes,
 Rolf

**Comment by kaythriemer** [comment]
Hi Rolf,
thank you for your very fast reply. OK, I will try the complete package.
Nevertheless I will try to find out, what is wrong with my environment ;-)

Thank you,

All the best,
Kay

**Comment by Rolf-Hempel** [comment]
Hi Kay,

It's certainly better to use the latest release. Even if you were an expert Python programmer, you would have to deal with many untested parts of the current source code.

I'm currently working on a new release which will contain many new features. The most important one is "auto-alignment" which uses computer vision to replace the user in the repeated alignments of the telescope pointing. (The "Image" module missing in your environment has to do with that.) That's pretty cool stuff, but so far I didn't test it on the moon yet. I plan to release the new version in a few months.

All the best,
 Rolf

**Comment by kaythriemer** [comment]
Hi Rolf,
OK I understand. This sounds like a very fascinating enhancement of your program. 
Till then I will familiarise with the latest release of MoonPanoramaMaker.
Thank you,
Kay
