### ISSUE TITLE
DLL error

### ISSUE THREAD

**Issue by lukesms** [Rolf-Hempel/MoonPanoramaMaker#6]
Hi,
Just downloaded and installed MPM and can't get it running, I see the plugin in FC but when I try to actually launch MPM I get an error splash screen, log below, seems to be a DLL issue of some sort, thanks for any help.

Traceback (most recent call last):
  File "moon_panorama_maker.py", line 27, in <module>
  File "PyQt4\QtGui.pyc", line 12, in <module>
  File "PyQt4\QtGui.pyc", line 10, in __load
ImportError: DLL load failed: The operating system cannot run %1.

**Comment by Rolf-Hempel** [comment]
Hi,
With the limited information given it is impossible to track down the problem. You did not even mention the OS version. Most likely, however, your ASCOM driver is not working properly. [In this thread](https://www.cloudynights.com/topic/534430-automatic-lunar-mosaicing/page-3) there are many discussions on similar problems.

I'm in the process of preparing a new release (MPM 1.0.0) both for Windows and Linux. Apart from many other improvements it gives much better diagnostic messages in case something goes wrong. So, perhaps the best idea in your case is to wait for the new release.

Best regards,
 Rolf

**Comment by lukesms** [comment]
I didn't see what info you would need, it's windows 10 ascom platform 6, I
currently use it with eqmod and stellarium scope for control and phd2 for
guiding with no issues... Maybe I'll just wait for v 1 to come out, are we
talking like weeks or months for that? Thanks.

**Comment by Rolf-Hempel** [comment]
I think it will take two weeks at most to finalize the release. So, I guess it would be best to wait for that.

On Windows 10 MPM 0.9.3 only worked in compatibility mode. But for 0.9.5 that should not be a problem any more. Version 1.0 should work just fine on Windows 7, 8, and 10. 90% of all problems users reported so far could be traced down to ASCOM configuration issues. The new MPM version tried to identify that by itself. I hope that will help in your case as well.

All the best,
 Rolf

**Comment by Rolf-Hempel** [comment]
I just released [V1.0.0](https://github.com/Rolf-Hempel/MoonPanoramaMaker/releases). I suggest that you de-install the previous version and try the new one. The program should not crash any more but give you a meaningful error message. Good luck!

**Comment by lukesms** [comment]
Yup V1.0.0 seems to have taken care of the issues, I can launch, and ran a couple frames through simulation.
