### ISSUE TITLE
Error when trying to add new camera config

### ISSUE THREAD

**Issue by Ryan-Bohner** [Rolf-Hempel/MoonPanoramaMaker#7]
I received this error:

Traceback (most recent call last):
  File "camera_configuration_input.py", line 141, in accept
AttributeError: 'CameraConfigurationInput' object has no attribute 'section_name'

I would love to help but I'm not familiar with Python, I mostly use c#.

**Comment by Rolf-Hempel** [comment]
Hi Ryan,

Thank you very much for your notification. This is a bug indeed, and it was easy to fix.

For now the corrected code is on the [development branch](https://github.com/Rolf-Hempel/MoonPanoramaMaker/tree/development) only. I will make a new release shortly with the usual installer files. Stay tuned!

All the best,
 Rolf

**Comment by Rolf-Hempel** [comment]
Hi Ryan,

I just published the Release 1.0.1 which should fix the bug you reported. I would appreciate your feedback if this solved your problem.

Best wishes,
 Rolf
